name: mushroomroulette
title: Mushroom Roulette
version: "1.3"
summary: Mushroom Roulette is a level based 2D top-down puzzle game.
description: |
	Use the mouse/touchscreen to click places for the player to move to or use
	your keyboard arrow keys.

	If using a touch screen it is reccomended you drag your path for the play
	to move along.

	Escape (Esc) takes you back to the menu.

grade: stable
icon: snap/gui/mushroomroulette.png

base: core18
confinement: strict

architectures:
  - build-on: amd64
  - build-on: i386

environment:
  WINEDLLOVERRIDES: "$WINEDLLOVERRIDES;mscoree,mshtml="    # Prevent pop-ups about Wine Mono and Wine Gecko

apps:
  photoscape:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier run-exe
    environment:
      INSTALL_EXE: "$SNAP/MushroomRoulette.exe"
  wine:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier run-exe
  winetricks:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier run-exe

parts:
  installer:
    plugin: dump
    source: installer

  # The sommelier script helps you snap Windows applications using Wine. It 
  # initializes and configures Wine and installs the Windows application.
  sommelier:
    plugin: make
    source: https://github.com/snapcrafters/sommelier-core.git

# These plugs are used to connect the snap to the wine runtime.
plugs:
  wine-runtime:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime
  wine-5-stable:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-5-stable
